# Generated by Django 5.2.8 on 2025-12-04 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: PETR4, HGLG11, CDB Banco X', max_length=20)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'Fundo Imobiliário (FII)'), ('renda_fixa', 'Renda Fixa / Tesouro'), ('crypto', 'Criptomoeda'), ('fundo', 'Fundo de Investimento'), ('exterior', 'Stocks / REITs')], max_length=20)),
                ('quantidade_atual', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nubank, Visa Platinum', max_length=50)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.IntegerField(help_text='Dia que a fatura fecha (1-31)')),
                ('dia_vencimento', models.IntegerField(help_text='Dia que a fatura vence (1-31)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
                ('categoria', models.CharField(choices=[('salario', 'Salário'), ('freela', 'Freelance/Extra'), ('investimento', 'Investimentos'), ('moradia', 'Moradia/Contas'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('parcelas', models.IntegerField(default=1, verbose_name='Qtde Parcelas')),
                ('parcela_atual', models.IntegerField(default=1)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.cartaocredito')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Dividendos/Rendimentos')], max_length=1)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='core.ativo')),
            ],
        ),
    ]
