# Generated by Django 5.2.8 on 2025-12-25 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ativo_cartaocredito_despesacartao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(help_text='Ex: Trocar de Moto, Viagem', max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depósito da 1ª Semana')),
                ('incremento', models.DecimalField(decimal_places=2, help_text='Quanto aumenta o depósito a cada semana?', max_digits=10, verbose_name='Aumento por Semana')),
                ('duracao_semanas', models.IntegerField(default=52, verbose_name='Duração (Semanas)')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemanaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_prevista', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='core.desafio')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
