# Generated by Django 5.2.8 on 2025-12-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_desafio_semanadesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='setor',
            field=models.CharField(blank=True, help_text='Ex: Bancos, Logística, Tecnologia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='cor_cartao',
            field=models.CharField(default='#4e73df', max_length=7, verbose_name='Cor do Cartão'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_fechamento',
            field=models.IntegerField(default=1, help_text='Dia que a fatura fecha (1-31)'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='cor',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
