# Generated by Django 5.2.8 on 2025-12-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contapagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='codigo',
        ),
        migrations.AddField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(default='Default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativo',
            name='setor',
            field=models.CharField(blank=True, help_text='Ex: Bancos, Logística', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'Ação B3'), ('FII', 'Fundo Imobiliário'), ('ETF', 'ETF'), ('CRIPTO', 'Criptomoeda')], max_length=10),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='incremento',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aumento por Semana'),
        ),
        migrations.CreateModel(
            name='AnaliseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now=True)),
                ('preco_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('divida_liquida_pl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('criterio_dy', models.BooleanField(default=False)),
                ('criterio_pl', models.BooleanField(default=False)),
                ('criterio_pvp', models.BooleanField(default=False)),
                ('criterio_roe', models.BooleanField(default=False)),
                ('criterio_divida', models.BooleanField(default=False)),
                ('pontuacao', models.IntegerField(default=0)),
                ('recomendacao', models.CharField(default='AGUARDAR', max_length=50)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='core.ativo')),
            ],
        ),
    ]
