# Generated by Django 5.2.8 on 2026-01-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ativo_codigo_ativo_ticker_alter_ativo_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='duracao_semanas',
            field=models.IntegerField(default=12, verbose_name='Duração (Semanas)'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='incremento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aumento por Semana'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Depósito da 1ª Semana'),
        ),
        migrations.AlterField(
            model_name='semanadesafio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
