# Generated by Django 5.2.8 on 2026-01-02 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_desafio_duracao_semanas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da primeira compra para cálculo de dividendos'),
        ),
    ]
